import { useState } from 'react';
import { ArrowRight, CheckCircle2, ChevronRight, Database, Menu, Sparkles, X, BarChart3, BrainCircuit, Boxes, Bot } from './components/Icons';
import Dashboard from './components/Dashboard';
import ChatDemo from './components/ChatDemo';
import { insights } from './data/mockData';

const problems=[['Too Much Data','Sales, customers, products, and reports spread across files.','◫'],['Manual Analysis','Time spent looking for answers instead of running the business.','⌁'],['No Data Specialist','Useful patterns stay hidden without an analytics expert.','◉'],['Slow Decisions','Critical stock and sales changes are noticed too late.','↗']];
const steps=[['01','Connect your data','Bring sales, customer, and inventory data together in one secure place.',Database],['02','AI analyzes your business','Detect patterns, opportunities, and issues across your performance.',BrainCircuit],['03','Get clear insights','Understand what matters through plain-language insights, not spreadsheets.',BarChart3],['04','Take better decisions','Turn insights into practical recommendations and confident next steps.',CheckCircle2]];
const features=[['Smart Sales Analytics','Spot trends, performance shifts, and the products moving your business forward.',BarChart3],['Customer Analytics','Understand customer value, behavior, and retention opportunities.',Bot],['Inventory Intelligence','Stay ahead of stock risk using sales velocity and timely alerts.',Boxes],['AI Recommendations','Get practical next-step recommendations based on your own data.',Sparkles],['Sales Forecasting','Plan ahead with understandable, data-informed sales forecasts.',BrainCircuit],['Natural Language Questions','Ask business questions naturally and get evidence-led answers.',Bot]];
function ScrollButton({children,target,outline=false}){return <button className={'button '+(outline?'outline':'')} onClick={()=>document.querySelector(target)?.scrollIntoView({behavior:'smooth'})}>{children}<ArrowRight size={17}/></button>}
export default function App(){const [open,setOpen]=useState(false);return <><header><a href="#top" className="logo"><span className="brand-mark">J</span><span>Jordan AI Data<br/><b>Assistant</b></span></a><nav className={open?'shown':''}><a href="#how" onClick={()=>setOpen(false)}>How it works</a><a href="#demo" onClick={()=>setOpen(false)}>Dashboard</a><a href="#insights" onClick={()=>setOpen(false)}>AI insights</a><a href="#future" onClick={()=>setOpen(false)}>Vision</a><ScrollButton target="#demo">Explore demo</ScrollButton></nav><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header>
<main id="top"><section className="hero"><div className="hero-copy"><div className="pill"><Sparkles size={15}/> Business intelligence, made clear</div><h1>Turn Your Business Data Into <span>Smarter Decisions.</span></h1><p>Jordan AI Data Assistant helps small and medium-sized businesses analyze sales, customers, inventory, and performance — then turn complex data into clear actions.</p><div className="hero-actions"><ScrollButton target="#demo">Get started</ScrollButton><ScrollButton target="#demo" outline>View demo</ScrollButton></div><div className="trust"><span><CheckCircle2/>Built for business owners</span><span><CheckCircle2/>No data expertise required</span></div></div><div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="float-card insight-float"><span><Sparkles size={15}/></span><div><small>AI INSIGHT GENERATED</small><b>Sales opportunity detected</b></div></div><div className="mini-dashboard"><div className="mini-head"><div><span className="mini-label">THIS MONTH</span><b>Business overview</b></div><span className="pulse"/></div><div className="mini-metrics"><div><small>Revenue</small><b>JOD 18,700</b><em>↑ 8.5%</em></div><div><small>Customers</small><b>846</b><em>↑ 5.2%</em></div></div><div className="mini-chart">{[45,68,54,82,63,95,72].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="mini-footer"><span><i/> Sales forecast</span><b>+8.5% next month</b></div></div></div></section>
<section className="problem section"><div className="section-intro centered"><span className="eyebrow">THE CHALLENGE</span><h2>Your Business Has Data. <span>But Do You Have the Right Decisions?</span></h2><p>The problem is not a lack of data. It is the difficulty of understanding it quickly enough to act with confidence.</p></div><div className="problem-grid">{problems.map(([title,text,icon])=><article className="problem-card" key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="solution section" id="how"><div className="section-intro"><span className="eyebrow">HOW IT WORKS</span><h2>Meet Your <span>Jordan AI Data Assistant.</span></h2><p>One intelligent workflow that turns the data you already have into your next best decision.</p></div><div className="steps">{steps.map(([num,title,text,Icon])=><article className="step" key={num}><span className="step-number">{num}</span><div className="step-icon"><Icon size={23}/></div><h3>{title}</h3><p>{text}</p><ChevronRight className="step-arrow"/></article>)}</div></section>
<section className="dashboard-section section"><div className="section-intro split"><div><span className="eyebrow">INTERACTIVE DEMO</span><h2>Your business, <span>clearly understood.</span></h2></div><p>See revenue, sales, customer and inventory health in one focused workspace — with the answers that deserve your attention first.</p></div><Dashboard/></section>
<section className="insights-section section" id="insights"><div className="section-intro centered"><span className="eyebrow">ALWAYS ANALYZING</span><h2>AI-Powered <span>Business Insights.</span></h2><p>Proactive signals explain what changed, why it matters, and what to do next.</p></div><div className="insights-grid">{insights.map((item,i)=><article className={'insight-card i'+i} key={item.type}><div className="insight-icon">{i===0?'↘':i===1?'▣':i===2?'◌':'✦'}</div><span>{item.type}</span><h3>{item.title}</h3><p>{item.detail}</p><button>Explore insight <ArrowRight size={14}/></button></article>)}</div></section>
<section className="chat-section section"><div className="chat-copy"><span className="eyebrow">NATURAL LANGUAGE INTELLIGENCE</span><h2>Ask Your <span>Business Anything.</span></h2><p>Have a conversation with the context of your data behind every answer. No dashboards to decode, no formulas to learn.</p><div className="chat-benefits"><span><CheckCircle2/>Answers grounded in your business data</span><span><CheckCircle2/>Clear explanations, not technical jargon</span><span><CheckCircle2/>Recommendations you can act on</span></div></div><ChatDemo/></section>
<section className="features section"><div className="section-intro centered"><span className="eyebrow">BUILT FOR BETTER DECISIONS</span><h2>Everything you need to <span>see what matters.</span></h2></div><div className="features-grid">{features.map(([title,text,Icon])=><article key={title}><div><Icon size={20}/></div><h3>{title}</h3><p>{text}</p><a href="#demo">Learn more <ArrowRight size={14}/></a></article>)}</div></section>
<section className="workflow section"><div className="section-intro centered"><span className="eyebrow">A BETTER WAY TO WORK</span><h2>From data overload to <span>decisive action.</span></h2></div><div className="workflow-grid"><article><span>TRADITIONAL WORKFLOW</span><div className="flow muted-flow"><b>Data</b><i>→</i><b>Excel</b><i>→</i><b>Manual Analysis</b><i>→</i><b>Decision</b></div><p>Slow, fragmented, and dependent on time you do not have.</p></article><article className="ai-flow"><span>AI BUSINESS ASSISTANT</span><div className="flow"><b>Data</b><i>→</i><b>AI Analysis</b><i>→</i><b>Insight</b><i>→</i><b>Recommendation</b><i>→</i><b>Decision</b></div><p>Connected insight that keeps pace with your business.</p></article></div></section>
<section className="jordan section"><div><span className="eyebrow">MADE FOR LOCAL AMBITION</span><h2>Built with small and medium businesses in <span>Jordan</span> in mind.</h2><p>For retailers, shops, restaurants, e-commerce, service businesses, and SMEs that have data — but not a dedicated data analyst.</p></div><div className="jordan-list"><span>Understand your data</span><span>Reduce manual analysis</span><span>Make faster decisions</span><span>Improve inventory planning</span><span>Understand customers</span><span>Forecast sales</span></div></section>
<section className="different section"><div className="different-card"><div><span className="eyebrow">MORE THAN A CHATBOT</span><h2>Built around your business — <span>not generic answers.</span></h2><p>Jordan AI Data Assistant combines your company data, analytics, dashboard, and recommendations into one decision-support system.</p></div><div className="component-map"><b>Company Data</b><i>+</i><b>AI</b><i>+</i><b>Analytics</b><i>+</i><b>Recommendations</b><strong>Better business decisions</strong></div></div></section>
<section className="future section" id="future"><div className="section-intro"><span className="eyebrow">FUTURE VISION</span><h2>From Business Assistant to <span>Business Decision Platform.</span></h2></div><div className="future-tags">{['POS & ERP integrations','Excel integration','WhatsApp Business','Arabic AI Assistant','Advanced forecasting','Automated reports','Multi-company support','Role-based access','Mobile application'].map(x=><span key={x}>{x}</span>)}</div></section>
<section className="final-cta"><div className="cta-glow"/><span className="eyebrow">YOUR NEXT DECISION STARTS HERE</span><h2>Your Data Already Knows <span>the Answer.</span></h2><p>Jordan AI Data Assistant helps you find it.</p><div><ScrollButton target="#demo">Explore the demo</ScrollButton><ScrollButton target="#top" outline>Start your business journey</ScrollButton></div></section></main><footer><a href="#top" className="logo"><span className="brand-mark">J</span><span>Jordan AI Data<br/><b>Assistant</b></span></a><p>AI-powered decisions for growing businesses.</p><small>Prototype MVP · Built for Jordan’s SMEs</small></footer></>}
